### ISSUE TITLE
Mentions are applied after banphrases

### ISSUE THREAD

**Issue by Mm2PL** [Supinic/supi-core#2]
https://github.com/Supinic/supi-core/blob/c7b95dd7f28be09cbfa6043c9fee775471481ee1/classes/command.js#L499-L502
https://github.com/Supinic/supi-core/blob/c7b95dd7f28be09cbfa6043c9fee775471481ee1/classes/command.js#L534-L544
Mentions should be applied before banphrases to not have usernames trigger pajbot banphrases.
![Supibot getting timed out for mentioning a user](https://i.imgur.com/i5eiyXK.png)

Found by @fawcan, I read the code.

**Comment by Supinic** [comment]
Fixed in a74accd9c027ee90b7e222cfc926b01c64946bd9
